"""UART host for loading matrices, starting the FPGA accelerator, and validating C.

Protocol used by this host is intentionally simple and byte-oriented:
  LOAD_A        b"A" + addr_u32 + data_i32 -> ACK
  LOAD_B        b"B" + addr_u32 + data_i32 -> ACK
  START         b"S"                       -> ACK
  READ_STATUS   b"?"                       -> status_u32
  READ_C        b"R" + addr_u32            -> data_i32
  READ_COUNTERS b"P"                       -> 6 x u32, if implemented by the FPGA

Words are big-endian. Signed values are sent as 32-bit two's-complement words;
the FPGA may keep only the lower DATA_WIDTH bits for A/B.
"""

from __future__ import annotations

import argparse
import json
import shutil
import struct
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

try:
    from .matrix_io import MatrixInputFile, MatrixTest, multiply_matrices
    from .matrix_io import read_expected_file, read_input_file, write_expected_file
except ImportError:
    from matrix_io import MatrixInputFile, MatrixTest, multiply_matrices
    from matrix_io import read_expected_file, read_input_file, write_expected_file

try:
    from config.project_config import PROJECT_ROOT
except ImportError:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from config.project_config import PROJECT_ROOT


CMD_LOAD_A = b"A"
CMD_LOAD_B = b"B"
CMD_START = b"S"
CMD_READ_STATUS = b"?"
CMD_READ_C = b"R"
CMD_READ_COUNTERS = b"P"
ACK = b"\x06"

STATUS_BUSY_MASK = 0x00000001
STATUS_DONE_MASK = 0x00000002


@dataclass(frozen=True)
class ValidationResult:
    passed: bool
    total_elements: int
    num_errors: int
    first_error: dict[str, int] | None


class HostLog:
    def __init__(self, path: Path) -> None:
        self.path = path
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._lines: list[str] = []

    def log(self, message: str) -> None:
        timestamp = datetime.now(timezone.utc).isoformat()
        line = f"{timestamp} {message}"
        self._lines.append(line)
        print(message)

    def flush(self) -> None:
        self.path.write_text("\n".join(self._lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Send matrix tests to the FPGA over UART and validate the result."
    )
    parser.add_argument("--port", help="Serial port, for example COM5 or /dev/ttyUSB0.")
    parser.add_argument("--baudrate", type=int, default=115200, help="UART baudrate. Default: 115200.")
    parser.add_argument(
        "--input",
        type=Path,
        default=PROJECT_ROOT / "matrix" / "matrix_inputs.txt",
        help="Input matrix file generated by golden_model.py.",
    )
    parser.add_argument(
        "--expected",
        type=Path,
        default=PROJECT_ROOT / "matrix" / "matrix_expected.txt",
        help="Expected output file generated by golden_model.py.",
    )
    parser.add_argument("--timeout", type=float, default=30.0, help="Timeout in seconds. Default: 30.")
    parser.add_argument(
        "--log-dir",
        type=Path,
        default=PROJECT_ROOT / "runs",
        help="Directory where run folders are created.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Run locally without opening a UART.")
    parser.add_argument("--run-id", help="Optional run directory name.")
    parser.add_argument("--tile-size", type=int, help="Optional TILE_SIZE metadata.")
    parser.add_argument("--num-macs", type=int, help="Optional NUM_MACS metadata.")
    parser.add_argument("--memory-burst-len", type=int, help="Optional MEMORY_BURST_LEN metadata.")
    parser.add_argument("--seed", type=int, help="Optional seed metadata.")
    parser.add_argument(
        "--read-counters",
        action="store_true",
        help="Request READ_COUNTERS after done. Use only if the FPGA command interface supports it.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.dry_run and not args.port:
        raise SystemExit("--port is required unless --dry-run is used")

    run_id = args.run_id or make_run_id()
    run_dir = unique_run_dir(args.log_dir / run_id)
    log = HostLog(run_dir / "host_log.txt")

    host_start = time.perf_counter()
    input_data = read_input_file(args.input)
    expected_data = read_expected_file(args.expected)
    validate_headers(input_data, expected_data)

    copy_to_run_dir(args.input, run_dir / "matrix_inputs.txt")
    copy_to_run_dir(args.expected, run_dir / "matrix_expected.txt")

    log.log(f"Run ID: {run_dir.name}")
    log.log(f"Loaded input file: {args.input}")
    log.log(f"Loaded expected file: {args.expected}")
    source_metadata = load_source_metadata(args.input)

    counters: dict[str, int] = {}
    if args.dry_run:
        received_tests = run_dry(input_data, log)
    else:
        received_tests, counters = run_uart(input_data, args, log)

    fpga_output_file = run_dir / "fpga_output.txt"
    write_expected_file(
        fpga_output_file,
        received_tests,
        n=input_data.n,
        acc_width=input_data.acc_width,
        generated_by="py_matrix_host.main uart",
    )

    validation = compare_results(received_tests, expected_data.tests, input_data.n)
    host_duration_s = time.perf_counter() - host_start
    validation_json = {
        "passed": validation.passed,
        "total_elements": validation.total_elements,
        "num_errors": validation.num_errors,
        "first_error": validation.first_error,
    }
    (run_dir / "validation.json").write_text(
        json.dumps(validation_json, indent=2), encoding="utf-8"
    )

    metadata = build_metadata(
        args=args,
        run_id=run_dir.name,
        input_data=input_data,
        host_duration_s=host_duration_s,
        counters=counters,
        source_metadata=source_metadata,
    )
    (run_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    log.log(f"FPGA output written to: {fpga_output_file}")
    log.log(f"Validation passed: {validation.passed}")
    log.log(f"Number of errors: {validation.num_errors}")
    log.log(f"Host total time seconds: {host_duration_s:.6f}")
    log.flush()

    if not validation.passed:
        raise SystemExit(1)


def make_run_id() -> str:
    return "run_" + datetime.now().strftime("%Y%m%d_%H%M%S")


def unique_run_dir(path: Path) -> Path:
    if not path.exists():
        path.mkdir(parents=True)
        return path

    suffix = 1
    while True:
        candidate = path.with_name(f"{path.name}_{suffix:02d}")
        if not candidate.exists():
            candidate.mkdir(parents=True)
            return candidate
        suffix += 1


def copy_to_run_dir(source: Path, destination: Path) -> None:
    source = source.resolve()
    destination = destination.resolve()
    if source == destination:
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def validate_headers(input_data: MatrixInputFile, expected_data) -> None:
    if input_data.num_tests != expected_data.num_tests:
        raise ValueError("Input and expected files have different NUM_TESTS")
    if input_data.n != expected_data.n:
        raise ValueError("Input and expected files have different N")
    if input_data.acc_width != expected_data.acc_width:
        raise ValueError("Input and expected files have different ACC_WIDTH")


def load_source_metadata(input_file: Path) -> dict[str, object]:
    metadata_file = input_file.parent / "metadata.json"
    if not metadata_file.exists():
        return {}
    try:
        data = json.loads(metadata_file.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    if isinstance(data, dict):
        return data
    return {}


def run_dry(input_data: MatrixInputFile, log: HostLog) -> list[MatrixTest]:
    log.log("Transmission start (dry-run)")
    received_tests: list[MatrixTest] = []

    for test in input_data.tests:
        if test.a is None or test.b is None:
            raise ValueError(f"TEST {test.index}: missing A or B matrix")
        log.log(f"TEST {test.index}: LOAD_A {input_data.n * input_data.n} words")
        log.log(f"TEST {test.index}: LOAD_B {input_data.n * input_data.n} words")
        log.log(f"TEST {test.index}: START sent")
        c = multiply_matrices(test.a, test.b)
        received_tests.append(MatrixTest(index=test.index, c=c))
        log.log(f"TEST {test.index}: done received")

    log.log("Transmission end (dry-run)")
    return received_tests


def run_uart(
    input_data: MatrixInputFile, args: argparse.Namespace, log: HostLog
) -> tuple[list[MatrixTest], dict[str, int]]:
    try:
        import serial
    except ImportError as exc:
        raise RuntimeError("pyserial is required for real UART mode: pip install pyserial") from exc

    received_tests: list[MatrixTest] = []
    counters: dict[str, int] = {}

    log.log("Transmission start")
    with serial.Serial(args.port, args.baudrate, timeout=args.timeout) as uart:
        for test in input_data.tests:
            if test.a is None or test.b is None:
                raise ValueError(f"TEST {test.index}: missing A or B matrix")

            log.log(f"TEST {test.index}: sending LOAD_A")
            send_matrix(uart, CMD_LOAD_A, test.a)
            log.log(f"TEST {test.index}: sending LOAD_B")
            send_matrix(uart, CMD_LOAD_B, test.b)

            send_command_ack(uart, CMD_START)
            log.log(f"TEST {test.index}: START sent")
            wait_for_done(uart, args.timeout)
            log.log(f"TEST {test.index}: done received")

            c = read_matrix_c(uart, input_data.n)
            received_tests.append(MatrixTest(index=test.index, c=c))

            if args.read_counters:
                counters = read_counters(uart)

    log.log("Transmission end")
    return received_tests, counters


def send_matrix(uart, command: bytes, matrix: list[list[int]]) -> None:
    for row_index, row in enumerate(matrix):
        for col_index, value in enumerate(row):
            addr = row_index * len(row) + col_index
            payload = command + pack_u32(addr) + pack_word(value)
            send_command_ack(uart, payload)


def send_command_ack(uart, payload: bytes) -> None:
    uart.write(payload)
    uart.flush()
    ack = read_exact(uart, 1)
    if ack != ACK:
        raise RuntimeError(f"Expected ACK 0x06, got 0x{ack.hex()}")


def wait_for_done(uart, timeout_s: float) -> None:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        uart.write(CMD_READ_STATUS)
        uart.flush()
        status = unpack_u32(read_exact(uart, 4))
        if status & STATUS_DONE_MASK:
            return
        time.sleep(0.01)

    raise TimeoutError("Timed out waiting for FPGA done status")


def read_matrix_c(uart, n: int) -> list[list[int]]:
    matrix: list[list[int]] = []
    for row in range(n):
        values: list[int] = []
        for col in range(n):
            addr = row * n + col
            uart.write(CMD_READ_C + pack_u32(addr))
            uart.flush()
            values.append(unpack_i32(read_exact(uart, 4)))
        matrix.append(values)
    return matrix


def read_counters(uart) -> dict[str, int]:
    names = [
        "total_cycles",
        "load_cycles",
        "compute_cycles",
        "store_cycles",
        "num_tiles_processed",
        "num_mac_ops_issued",
    ]
    uart.write(CMD_READ_COUNTERS)
    uart.flush()
    values = [unpack_u32(read_exact(uart, 4)) for _ in names]
    return dict(zip(names, values))


def read_exact(uart, size: int) -> bytes:
    data = uart.read(size)
    if len(data) != size:
        raise TimeoutError(f"Expected {size} byte(s), received {len(data)}")
    return data


def pack_u32(value: int) -> bytes:
    return struct.pack(">I", value & 0xFFFFFFFF)


def pack_word(value: int) -> bytes:
    return struct.pack(">I", value & 0xFFFFFFFF)


def unpack_u32(data: bytes) -> int:
    return struct.unpack(">I", data)[0]


def unpack_i32(data: bytes) -> int:
    value = unpack_u32(data)
    if value & 0x80000000:
        value -= 0x100000000
    return value


def compare_results(
    received_tests: list[MatrixTest], expected_tests: list[MatrixTest], n: int
) -> ValidationResult:
    expected_by_index = {test.index: test for test in expected_tests}
    num_errors = 0
    total_elements = 0
    first_error: dict[str, int] | None = None

    for received in received_tests:
        expected = expected_by_index.get(received.index)
        if expected is None or expected.c is None:
            raise ValueError(f"Missing expected matrix for TEST {received.index}")
        if received.c is None:
            raise ValueError(f"Missing received matrix for TEST {received.index}")

        for row in range(n):
            for col in range(n):
                total_elements += 1
                expected_value = expected.c[row][col]
                received_value = received.c[row][col]
                if expected_value != received_value:
                    num_errors += 1
                    if first_error is None:
                        first_error = {
                            "test": received.index,
                            "row": row,
                            "col": col,
                            "expected": expected_value,
                            "received": received_value,
                        }

    return ValidationResult(
        passed=num_errors == 0,
        total_elements=total_elements,
        num_errors=num_errors,
        first_error=first_error,
    )


def build_metadata(
    *,
    args: argparse.Namespace,
    run_id: str,
    input_data: MatrixInputFile,
    host_duration_s: float,
    counters: dict[str, int],
    source_metadata: dict[str, object],
) -> dict[str, object]:
    seed = args.seed if args.seed is not None else source_metadata.get("seed")
    metadata: dict[str, object] = {
        "run_id": run_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "N": input_data.n,
        "DATA_WIDTH": input_data.data_width,
        "ACC_WIDTH": input_data.acc_width,
        "TILE_SIZE": args.tile_size,
        "NUM_MACS": args.num_macs,
        "MEMORY_BURST_LEN": args.memory_burst_len,
        "seed": seed,
        "dry_run": args.dry_run,
        "port": None if args.dry_run else args.port,
        "baudrate": args.baudrate,
        "timeout_s": args.timeout,
        "host_duration_s": host_duration_s,
        "protocol": {
            "endianness": "big",
            "commands": {
                "LOAD_A": "0x41",
                "LOAD_B": "0x42",
                "START": "0x53",
                "READ_STATUS": "0x3f",
                "READ_C": "0x52",
                "READ_COUNTERS": "0x50",
            },
            "status_bits": {
                "busy": 0,
                "done": 1,
            },
        },
    }
    if counters:
        metadata["counters"] = counters
    if source_metadata:
        metadata["source_metadata"] = source_metadata
    return metadata


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"UART host failed: {exc}", file=sys.stderr)
        raise
