"""Matrix text format helpers used by the golden model and UART host."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class MatrixTest:
    index: int
    a: list[list[int]] | None = None
    b: list[list[int]] | None = None
    c: list[list[int]] | None = None


@dataclass(frozen=True)
class MatrixInputFile:
    num_tests: int
    n: int
    data_width: int
    acc_width: int
    tests: list[MatrixTest]


@dataclass(frozen=True)
class MatrixExpectedFile:
    num_tests: int
    n: int
    acc_width: int
    tests: list[MatrixTest]


def signed_range_for_width(width: int) -> tuple[int, int]:
    if width <= 0:
        raise ValueError("width must be greater than zero")
    return -(2 ** (width - 1)), (2 ** (width - 1)) - 1


def multiply_matrices(a: list[list[int]], b: list[list[int]]) -> list[list[int]]:
    rows_a = len(a)
    cols_a = len(a[0]) if rows_a else 0
    rows_b = len(b)
    cols_b = len(b[0]) if rows_b else 0

    if cols_a != rows_b:
        raise ValueError("Matrix sizes are incompatible: A columns must match B rows")

    return [
        [sum(a[row][k] * b[k][col] for k in range(cols_a)) for col in range(cols_b)]
        for row in range(rows_a)
    ]


def format_matrix(name: str, matrix: list[list[int]]) -> str:
    rows = len(matrix)
    cols = len(matrix[0]) if rows else 0
    body = "\n".join(" ".join(str(value) for value in row) for row in matrix)
    return f"{name} {rows} {cols}\n{body}\n"


def write_input_file(
    path: Path,
    tests: Iterable[MatrixTest],
    *,
    n: int,
    data_width: int,
    acc_width: int,
    seed: int,
    min_value: int,
    max_value: int,
) -> None:
    tests = list(tests)
    path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        "# Matrix inputs generated by golden_model.py\n"
        "# layout=row-major input_type=signed_int\n"
        f"# seed={seed} num_tests={len(tests)} n={n}\n"
        f"# min_value={min_value} max_value={max_value}\n\n"
        f"NUM_TESTS {len(tests)}\n"
        f"N {n}\n"
        f"DATA_WIDTH {data_width}\n"
        f"ACC_WIDTH {acc_width}\n\n"
    )
    body = "\n".join(_format_input_test(test) for test in tests)
    path.write_text(header + body, encoding="utf-8")


def write_expected_file(
    path: Path,
    tests: Iterable[MatrixTest],
    *,
    n: int,
    acc_width: int,
    generated_by: str = "golden_model.py",
) -> None:
    tests = list(tests)
    path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        f"# Expected output generated by {generated_by}\n"
        "# C = A x B\n"
        "# layout=row-major output_type=signed_int\n\n"
        f"NUM_TESTS {len(tests)}\n"
        f"N {n}\n"
        f"ACC_WIDTH {acc_width}\n\n"
    )
    body = "\n".join(_format_output_test(test) for test in tests)
    path.write_text(header + body, encoding="utf-8")


def read_input_file(path: Path) -> MatrixInputFile:
    tokens = _read_tokens(path)
    header, index = _parse_header(tokens)
    tests: list[MatrixTest] = []

    while index < len(tokens):
        _expect(tokens[index], "TEST", path)
        test_index = int(tokens[index][1])
        index += 1

        name, a, index = _parse_matrix(tokens, index, path)
        if name != "A":
            raise ValueError(f"{path}: expected matrix A in TEST {test_index}, got {name}")

        name, b, index = _parse_matrix(tokens, index, path)
        if name != "B":
            raise ValueError(f"{path}: expected matrix B in TEST {test_index}, got {name}")

        _expect(tokens[index], "END_TEST", path)
        index += 1
        tests.append(MatrixTest(index=test_index, a=a, b=b))

    num_tests = _header_int(header, "NUM_TESTS", len(tests))
    n = _header_int(header, "N", len(tests[0].a or []) if tests else 0)
    data_width = _header_int(header, "DATA_WIDTH", 8)
    acc_width = _header_int(header, "ACC_WIDTH", 32)

    _validate_test_count(path, num_tests, tests)
    for test in tests:
        _validate_square(path, "A", test.a, n)
        _validate_square(path, "B", test.b, n)

    return MatrixInputFile(
        num_tests=num_tests,
        n=n,
        data_width=data_width,
        acc_width=acc_width,
        tests=tests,
    )


def read_expected_file(path: Path) -> MatrixExpectedFile:
    tokens = _read_tokens(path)
    header, index = _parse_header(tokens)
    tests: list[MatrixTest] = []

    while index < len(tokens):
        _expect(tokens[index], "TEST", path)
        test_index = int(tokens[index][1])
        index += 1

        name, c, index = _parse_matrix(tokens, index, path)
        if name != "C":
            raise ValueError(f"{path}: expected matrix C in TEST {test_index}, got {name}")

        _expect(tokens[index], "END_TEST", path)
        index += 1
        tests.append(MatrixTest(index=test_index, c=c))

    num_tests = _header_int(header, "NUM_TESTS", len(tests))
    n = _header_int(header, "N", len(tests[0].c or []) if tests else 0)
    acc_width = _header_int(header, "ACC_WIDTH", 32)

    _validate_test_count(path, num_tests, tests)
    for test in tests:
        _validate_square(path, "C", test.c, n)

    return MatrixExpectedFile(num_tests=num_tests, n=n, acc_width=acc_width, tests=tests)


def _format_input_test(test: MatrixTest) -> str:
    if test.a is None or test.b is None:
        raise ValueError("input tests must contain matrices A and B")
    return (
        f"TEST {test.index}\n"
        f"{format_matrix('A', test.a)}"
        f"\n{format_matrix('B', test.b)}"
        "END_TEST\n"
    )


def _format_output_test(test: MatrixTest) -> str:
    if test.c is None:
        raise ValueError("expected/output tests must contain matrix C")
    return f"TEST {test.index}\n{format_matrix('C', test.c)}END_TEST\n"


def _read_tokens(path: Path) -> list[list[str]]:
    tokens: list[list[str]] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        tokens.append(line.split())
    return tokens


def _parse_header(tokens: list[list[str]]) -> tuple[dict[str, list[str]], int]:
    header: dict[str, list[str]] = {}
    index = 0
    while index < len(tokens) and tokens[index][0] != "TEST":
        key, *values = tokens[index]
        header[key] = values
        index += 1
    return header, index


def _parse_matrix(
    tokens: list[list[str]], index: int, path: Path
) -> tuple[str, list[list[int]], int]:
    if index >= len(tokens):
        raise ValueError(f"{path}: expected matrix declaration, got end of file")

    declaration = tokens[index]
    if len(declaration) != 3:
        raise ValueError(f"{path}: invalid matrix declaration: {' '.join(declaration)}")

    name = declaration[0]
    rows = int(declaration[1])
    cols = int(declaration[2])
    index += 1

    matrix: list[list[int]] = []
    for row_index in range(rows):
        if index >= len(tokens):
            raise ValueError(f"{path}: matrix {name} ended before row {row_index}")
        row = [int(value) for value in tokens[index]]
        if len(row) != cols:
            raise ValueError(
                f"{path}: matrix {name} row {row_index} has {len(row)} values, expected {cols}"
            )
        matrix.append(row)
        index += 1

    return name, matrix, index


def _expect(tokens: list[str], expected: str, path: Path) -> None:
    if not tokens or tokens[0] != expected:
        got = " ".join(tokens) if tokens else "end of file"
        raise ValueError(f"{path}: expected {expected}, got {got}")


def _header_int(header: dict[str, list[str]], key: str, default: int) -> int:
    values = header.get(key)
    if not values:
        return default
    return int(values[0])


def _validate_test_count(path: Path, num_tests: int, tests: list[MatrixTest]) -> None:
    if num_tests != len(tests):
        raise ValueError(f"{path}: NUM_TESTS={num_tests}, but parsed {len(tests)} tests")


def _validate_square(path: Path, name: str, matrix: list[list[int]] | None, n: int) -> None:
    if matrix is None:
        raise ValueError(f"{path}: missing matrix {name}")
    if len(matrix) != n:
        raise ValueError(f"{path}: matrix {name} has {len(matrix)} rows, expected {n}")
    for row_index, row in enumerate(matrix):
        if len(row) != n:
            raise ValueError(
                f"{path}: matrix {name} row {row_index} has {len(row)} columns, expected {n}"
            )
